version: 2
jobs:
    build:
     docker:
        - image: python:3.8
          environment:
     steps:
        - checkout
        - run:
            name: deps
            command: |
                #apt install python-pip
                python3 -m pip install -U pip

        - run:
            name: build
            command: |
                python3 -m pip install -e . --user

        - run:
            name: dts help
            command: |
                 export PATH=/home/circleci/.local/bin:$PATH
                 dts help

        - run:
            name: dts version
            command: |
                 export PATH=/home/circleci/.local/bin:$PATH
                 dts version
